import os
import pandas as pd
import gdown
import zipfile

print("----------------------Table 2--------------------")
df = pd.read_excel("differences_group_by.xlsx")
print("Count of A :", df[df['WCAG level'] == 'A']['Code'].nunique())
print("Count of AA :", df[df['WCAG level'] == 'AA']['Code'].nunique())
print("---------------------------------------------------------------")
print("Count of 2.4.7 Focus Visible:", df[df['Checkpoint'] == '2.4.7 Focus Visible']['Code'].nunique())
print("Count of 2.4.1 Bypass Blocks:", df[df['Checkpoint'] == '2.4.1 Bypass Blocks']['Code'].nunique())
print("Count of 3.2.2 On Input:", df[df['Checkpoint'] == '3.2.2 On Input']['Code'].nunique())
print("Count of 1.1.1 Non-text Content:", df[df['Checkpoint'] == '1.1.1 Non-text Content']['Code'].nunique())
print("Count of 4.1.2 Name, Role, Value:", df[df['Checkpoint'] == '4.1.2 Name, Role, Value']['Code'].nunique())
print("Count of 2.4.4 Link Purpose (In Context):", df[df['Checkpoint'] == '2.4.4 Link Purpose (In Context)']['Code'].nunique())
print("Count of 1.3.4 Orientation:", df[df['Checkpoint'] == '1.3.4 Orientation']['Code'].nunique())
print("Count of 1.3.1 Info and Relationships:", df[df['Checkpoint'] == '1.3.1 Info and Relationships']['Code'].nunique())
print("Count of 2.1.1 Keyboard:", df[df['Checkpoint'] == '2.1.1 Keyboard']['Code'].nunique())
print("Count of 2.4.3 Focus Order:", df[df['Checkpoint'] == '2.4.3 Focus Order']['Code'].nunique())
print("Count of 1.4.3 Contrast (Minimum):", df[df['Checkpoint'] == '1.4.3 Contrast (Minimum)']['Code'].nunique())
print("Count of 2.5.3 Label in Name:", df[df['Checkpoint'] == '2.5.3 Label in Name']['Code'].nunique())
print("Count of 1.2.1 Audio-only and Video-only:", df[df['Checkpoint'] == '1.2.1 Audio-only and Video-only']['Code'].nunique())
print("Count of 1.2.4 Captions (Live):", df[df['Checkpoint'] == '1.2.4 Captions (Live)']['Code'].nunique())
print("Count of 1.4.1 Use of Color:", df[df['Checkpoint'] == '1.4.1 Use of Color']['Code'].nunique())
print("Count of 3.3.2 Labels or Instructions:", df[df['Checkpoint'] == '3.3.2 Labels or Instructions']['Code'].nunique())
print("Count of 1.3.3 Sensory Characteristics:", df[df['Checkpoint'] == '1.3.3 Sensory Characteristics']['Code'].nunique())
print("Count of 3.1.1 Language of Page:", df[df['Checkpoint'] == '3.1.1 Language of Page']['Code'].nunique())
print("Count of 1.4.12 Text Spacing:", df[df['Checkpoint'] == '1.4.12 Text Spacing']['Code'].nunique())
print("Count of 1.4.4 Resize text:", df[df['Checkpoint'] == '1.4.4 Resize text']['Code'].nunique())
print("Count of 2.1.2 No Keyboard Trap:", df[df['Checkpoint'] == '2.1.2 No Keyboard Trap']['Code'].nunique())
print("Count of 3.2.1 On Focus:", df[df['Checkpoint'] == '3.2.1 On Focus']['Code'].nunique())
print("Count of 2.4.2 Page Titled:", df[df['Checkpoint'] == '2.4.2 Page Titled']['Code'].nunique())
print("Count of 2.4.6 Headings and Labels:", df[df['Checkpoint'] == '2.4.6 Headings and Labels']['Code'].nunique())
print("Count of 1.3.2 Meaningful Sequence:", df[df['Checkpoint'] == '1.3.2 Meaningful Sequence']['Code'].nunique())
print("Count of 1.3.5 Identify Input Purpose:", df[df['Checkpoint'] == '1.3.5 Identify Input Purpose']['Code'].nunique())
print("Count of 2.2.1 Timing Adjustable:", df[df['Checkpoint'] == '2.2.1 Timing Adjustable']['Code'].nunique())
print("Count of 2.4.13 Content on Hover:", df[df['Checkpoint'] == '2.4.13 Content on Hover']['Code'].nunique())
print("---------------------------------------------------------------")